# Generated by Django 4.1.13 on 2024-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='fUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusername', models.CharField(max_length=255, null=True)),
                ('fpassword', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
